### ISSUE TITLE
Errors with mysql driver

### ISSUE THREAD

**Issue by ririko5834** [ffamilyfriendly/Thread-Watcher#68]
Hi, I am using remote mysql database from my webhosting provider and sometimes I get errors like this

```
node:27) DeprecationWarning: MessageEmbed#addField is deprecated and will be removed in the next major update. Use MessageEmbed#addFields instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
There was an uncaught error Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/container/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/home/container/node_modules/mysql/lib/Connection.js:94:28)
    at Socket.<anonymous> (/home/container/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
There was an uncaught error Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/home/container/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/home/container/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at Connection.query (/home/container/node_modules/mysql/lib/Connection.js:198:25)
    at /home/container/utils/db/mysql.js:78:21
    at new Promise (<anonymous>)
    at DatabaseExample.getThreadsInGuild (/home/container/utils/db/mysql.js:77:16)
    at Object.run (/home/container/commands/threads.js:11:30)
    at Client.<anonymous> (/home/container/index.js:158:11)
    at Client.emit (node:events:513:28)
    at InteractionCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:83:12) {
  code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR',
  fatal: false
}
There was an uncaught error Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/home/container/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/home/container/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at Connection.query (/home/container/node_modules/mysql/lib/Connection.js:198:25)
    at /home/container/utils/db/mysql.js:78:21
    at new Promise (<anonymous>)
    at DatabaseExample.getThreadsInGuild (/home/container/utils/db/mysql.js:77:16)
    at Object.run (/home/container/commands/threads.js:11:30)
    at Client.<anonymous> (/home/container/index.js:158:11)
    at Client.emit (node:events:513:28)
    at InteractionCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:83:12) {
  code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR',
  fatal: false
}
```

commands are failing and threads are not being reopened.

When I restart the bot it works for some time but then again this.

**Comment by ririko5834** [comment]
Can you fix it?

https://stackoverflow.com/questions/37619977/error-cannot-enqueue-query-after-fatal-error-in-mysql-node

**Comment by ffamilyfriendly** [comment]
I do not get the same error on my host but I'll make sure connection gets handled correctly when implementing MySQL on v2
